name: spritewidget_example
description: Demonstrates how to use the spritewidget plugin.
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  spritewidget:
    path: ../

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
